### ISSUE TITLE
ServerGroup broken with pulumi-openstack v3.12.0

### ISSUE THREAD

**Issue by tobiashenkel** [pulumi/pulumi-openstack#248]
### What happened?

After upgrade of pulumi-openstack from v3.11.0 to v3.12.0 the ServerGroup resource breaks rollout.

### Expected Behavior

Resource is created or shows no change in a pre-existing stack.

### Steps to reproduce

Create a stack with this example code and run `pulumi preview`:

```
server_group = ServerGroup(
    'example-group',
    policies=['anti-affinity'],
)
```

This is expected to succeed as it works with v3.11.0.

Actual result:
```
Previewing update (test)

View in Browser (Ctrl+O): (...)

     Type                 Name      Plan     Info
     pulumi:pulumi:Stack  dns-test           1 error


Diagnostics:
  pulumi:pulumi:Stack (dns-test):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "(...)/.pulumi/3.58.0/pulumi/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "(...)/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 136, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 120, in wait_for_rpcs
        raise exception
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 811, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 176, in prepare_resource
        serialized_props = await rpc.serialize_properties(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 208, in serialize_properties
        result = await serialize_property(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 260, in serialize_property
        element_type = _get_list_element_type(typ)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "(...)/.venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 161, in _get_list_element_type
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got '<class 'str'>
```

### Output of `pulumi about`

```
CLI
Version      3.58.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.28.0
kubernetes  3.23.1
openstack   3.12.0
python      unknown
random      4.10.0

Host
OS       darwin
Version  13.2.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tobiashenkel** [comment]
Thanks I confirm the fix is working 👍
